# Repository Name - hello-world-repo
# Work on the following branch - main
# Workflow File Name - hello-world.yml
# Workflow Name - Hello World
# Trigger Workflow on push events
# Workflow should have a Job named - hello-job
# a. Run Job on - ubuntu-latest runner
# b. Job has 1 step named - Echo text
# c. Run a command - echo "Hello, world!"
# Trigger Workflow on push event should execute successfully
name: Hello World
on:
  push:
jobs: 
  runs_on: ubuntu-latest
  steps:
  - name: Echo text
    run: echo "Hello, World!"